name: Run Unit Tests

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# The list of jobs to run as part of this workflow
jobs:
  test:
    # The type of machine to run on
    runs-on: ubuntu-latest

    # Steps to execute in the job
    steps:
      # Step 1: Check out the repository's code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run unit tests
      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "*_test.py"

      # Step 5: Collect test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./tests/__pycache__/
